#+TITLE: CCNP Notes
#+STARTUP: overview indent
* Part 1 Packet Forwarding
* Part 2 Layer 2
** Chapter 2 STP
*** IEEE 802.1D STP
Original version
*States:*
- Disabled: = shut down
- Blocking: enabled but not forwarding
- Listening: can send and receive BPDUs but doesn't forward traffic
- Learning: can modify the mac address table but doesn't forward traffic
- Forwarding: can froward traffic and update the mac table
- Broken: if a configuration or operational problem is detected. Discards all traffic
*port types*:
- Root Port (RP): connects to the root bridge or upstream switch
- Designated port (DP): receives and forwards BPDUs to other switches
- Blocking port: doesn't forward traffic
*terminology*:
- Root bridge: top of the tree, all ports forward
- Bridge protocol data unit (BPDU): packet used to identify hierarchy and notify changes
  - Configuration BPDU: used to identify the root bridge, root, designated and blocked ports. Has the fields STP type, root path cost, root bridge identifier, local bridge identifier, max age, hello time and forward delay
  - Topology change notifcation (TCN) BPDU: used to communicate topology changes
- root path cost: combined cost to the root switch
- system priority: indicates the preference for the root switch
- system id extension: indicates the vlan that the BPDU correlates to
- root bridge identifier: combination of the root bridge mac address, system id extension and system priority
- local bridge identifier: combination of the local switch's system mac address system id extension and system priority of the root bridge
- max age: maximum duration before the bridge saves its BPDU
- hello time: time that a BPDU is advertised
- forward delay: amount of time that a port stays in listening or learning states
*path cost*:
- short mode: reference speed of 20Gbps
- long mode: reference speed of 20Tbps
| link speed | short mode | long mode |
|------------+------------+-----------|
| 10 Mbps    |        100 |   2000000 |
| 100 Mbps   |         19 |    200000 |
| 1 Gbps     |          4 |     20000 |
| 10 Gbps    |          3 |      2000 |
| 20 Gbps    |          1 |      1000 |
| 100 Gbps   |          1 |       200 |
| 1 Tbps     |          1 |        20 |
| 10 Tbps    |          1 |         2 |
|------------+------------+-----------|
the entire L2 topology has to use the same cost mode!!
*** Building the STP Topology
**** Root bridge election
switches start thinking that they are root and update to the new root if they receive a preferred BPDU
this happens if the priority in the bridge identifier is lower than it's own. If they are the same, the system mac address wins
bridge priorities are composed by the configured priority + the sys-id-ext (vlan number)
**** Locating root port
the bridge uses following parameters to pick it's root port (in order, the next is only used if there is a tie):
1. lowest cost
2. lowest system priority of advertising switch
3. lowest system mac of advertising switch
4. if multiple links to the same switch, lowest priority wins
5. if multiple links to the same switch, lowest port number
**** Locating designated and blocked ports
To decide which ports should be blocked (in order, next step is used if tie):
1. the port should be a designated and not a RP
2. the switch with the lowest path cost to the root wins
3. system priority is compared
4. mac addresses are compared
*** Topology changes
if a switch detects a status change, it sends a TCN BPDU toward the root bridge
Upstream switches forward TCNs and send an ack to the sending switch
the root bridge creates a TCN BPDU and floods it to the whole topology
switches that received a TCN from the root set the mac address timer (default 15 seconds), this flushes all mac addresses that haven communicated for the timer time
this prevents the bridge from sending traffic a to a mac that is no longer reachable, increases unknown unicast traffic
mac timers are restored after the second BPDU
*** Rapid Spanning Tree Protocol (RSTP)
**** Port States
- Discarding: combines traditional disabled, blocking and listening
- Learning: modifies the mac table from incoming traffic but doesn't forward
- Forwarding: forwards traffic
**** Port Roles
- Root Port (RP): connects to the root or upstream switch
- Designated Port (DP): receives and forwards frames to other switches
- Alternate Port: provides alternate connectivity toward the root switch
- Backup port: provides link redundancy to the root.
**** Port types:
- Edge port: at the edge of the network where hosts connect
- Root port: best path cost toward the root
- Point-to-point port: Ports that connect to another RSTP switch with full duplex.
*** Building the RSTP Topology
RSTP handshake is used to transition through the states faster
1. check point-to-point (full duplex) status
2. establish handshake (config BPDUs) that their interface is DP
3. superior switch identification
4. inferior switch marks it's port as RP and moves all non-edge ports to discarding
5. inferior switch sends an agreement (config BPDU) to the root
6. inferior switch moves it's RP to forwarding
7. inferior switch repeats the process for other downstream ports

** Chapter 3 STP tuning
*** Root Bridge Placement
make the core root and the secondary so as to minimize changes to the tree
the command spanning-tree vlan _vlan-id_ root {primary | secondary} [diameter _diameter_ ] sets primary to 24576, secondary to 28672
the diameter command tunes the stp timers and the parameter is the number of L2 hops between the switch and the root. Timers config are carried through BPDUs
*** Modifying Root and Blocked ports locations
by modifying the cost is possible to trigger port type changes and modify the stp path.
*port priority* sets which port is alternate when multiple links are used between switches
*** Aditional STP protection mechanisms
** Chapter 4 MSTP
Multiple spanning tree protocol, maps multiple Vlans to one stp tree for performance optimization
original standard 802.1D also called CST (Common spanning tree)
Grouped Vlans are called regions
Regions appear as one single virtual switch to other stp entities
Uses a special instance (number 0) on ports of the MST regions
Information about other MSTs is nested on the BPDUs, optimizing traffic
*** common misconfigurations
- Vlan asignment to the IST
- Trunk link pruning

** Chapter 5 VLAN + Etherchannels
*** VTP (Virtual Trunking Protocol)
server-client protocol to deploy vlans on multiple switches
version 1, 2,3
**** Advertisements
- Summary: every 300 seconds when add, remove or changed
- Subset: when vlan config change
- client requests: request from a clien to get more information
**** Roles
- Server: responsible for creation, modification and deletion of vlans
- Client: receives information from server. Can't configure locally
- Transparent: sends and receives info but doesn't modify local config
- off: doesn't participate in VTP
*** DTP (Dynamic Trunking Protocol)
protocol to negotiate trunking capabilities
**** Modes
- Trunk: statically set to trunk and advertises DTP to the other part to become a trunk
- dynamic desirable: acts as access but listens and advertises to become a trunk
- dynamic auto: acts as access and listens but doesn't advertise
*** Etherchannel bundle
Logical grouping of physical ports. LACP and PAgP
max and min number of interfaces can be configured
**** PAgP
Modes:
- Auto: doesn't initiate but listens
- Desirable: tries to initiate
**** LACP
Modes:
- Passive: doesn't initiate but listens
- Active: tries to initiate

Options:
- LACP Fast: sends updates every 1 second
- system priority: sets up which is the master of the port channel. This switch is in charge of deciding which ports to use in case that the max amount is surpased
- interface priority: sets up which interface should be used in case where more interfaces than the max defined are available

* Part 3 Routing
** Chapter 6 IP Routing
*** Distance vector
uses hop count to determine the best route
advertise from their own perspective. No router has a complete overview of the network
*** Enhanced distance vector
sends updates only on change
fast convergence
forms neighbor relationships
uses bandwidth, delay, reliability, load, and mtu for path calculations
load balance between equal or unequal cost paths
*** Link state
advertises the link state and metric of each connected links
advertisements are stored in the link-state database (LSDB) and forwarded to other neighbors
with all the information each router runs the Dijkstra shortest path first algorithm to calculate the best loop free path
*** Path vector
looks at the path attributes to select best path
keeps record of each AS to avoid loops

*** Path selection
evaluates the prefix length in the Forwarding information base (FIB)
that is programmed via the routing table or Routing information base (RIB)
Components:
- prefix length: number of leading bits in the subnet mask
- administrative distance: rating of trustworthiness of a routing information source
- metric: unit of measure used by a routing protocol in best-path calculation
the forwarding decision is a function of the FIB and results from the
calculations performed in the RIB. The RIB is calculated though the combination of routing protocol metrics and administrative distance
Each routing protocol is it's own process and programs the RIB. Every protocol presents the same information to the RIB: destination network, next-hop, AD and metric.
Accepting logic:
- if the route doesn't exist is accepted
- if the route exists, ADs are compared and the lowest wins
**** Metrics
value assigned to a route by the routing protocol for best selection
***** ECMP (Equal cost multipathing)
a routing protocol selects multiple routes as best path and all get installed in the RIB
***** Unequal-cost load balancing
EIGRP allows the installation of multiple routes with different metrics
*** Static routing
manually configured
**** Directly attached routes
P2P routes don't use ARP and can directly reference the outbound interface.
requires that the outbound interface be in an up state to install the route
**** Recrusive static routes
specifies the ip of the netx-hop address. The recursion ocurrs when the router queries the
RIB to locathe the route to the next-hop and cross-references the adjacency table.
requires the next-hop address to exist in the routing table.
**** Fully specefied static routes
uses the outbound interface and next-hop ips
avoids recursion and makes the outbound interface deterministic
**** Floating static routing
used to provide a backup from dynamically learned routes
gets an AD higher than the one learned dynamically, so only gets installed if the dynamic
route fails.
**** Static null routes
Null interfaces drop traffic without cpu overhead
used to discard traffic and avoid routing loops when a default gateway is defined
*** IPv6 static routes
are the same as with IPv4
*** Virtual forwarding and routing (VRF)
creates separate virtual routers on a physical one
each virtual router maintains a separate routing table
** Chapter 7 EIGRP
has the concept of autonomus system, different from the bgp AS
each EIFRP process belongs to a autonomus system (routing domain)
*** Terminology
- successor route: route with the lowes path metric to reach a destination
- successor: first next-hop router for the successor route
- feasible distance FD: metric value for the lowest-metric path to reach a
  destination
- reported distance: distance reporter by a router to a prefix. This is the
  feasible distance for the advertising router.
- feasibility condition: a condition under which, for a route to be considered a
  backup route, the reported distance received for that route must be less than
  the feasible distance calculated locally. This is used to avoid loops.
*** Topology table
has all prefixes advertised within an EIGRP autonomus system. Contains:
- network prefix
- EIGRP neighbors that advertised that prefix
- Metrics from each neighbor
- values used for calculating the metric

 to select the best path, the FD (feasible distance) calculated by the switch,
  and the RD (reported distance) advertised by the neighbors is compared and the
  lowest one wins
*** EIGRP Neighbors
exchange the entire routing table when forming an adjacency and incremental
updates afterwards
uses ip protocol number 88
**** Packet types:
- Hello: discovery of neighbors
- Request: get specific information
- Update: transmit information
- Query: dent out to search for another path during convergence
- Reply: Sent in response to a query packet

** Chapter 8 OSPF
** Chapter 9 Advanced OSPF
** Chapter 10 OSPFv3
** Chapter 11 BGP
** Chapter 12 Advanced BGP
** Chapter 13 Multicast
* Part 4 Services
** Chapter 14 QoS
** Chapter 15 IP Services
* Part 5 Overlay
** Chapter 16 Overlay tunnels
* Part 6 Wireless
** Chapter 17 Signals and Modulation
** Chapter 18 Infrastructure
** Chapter 19 Roaming and location
** Chapter 20 Authentication
** Chapter 21 Troubleshooting
* Part 7 Architecture
** Chapter 22 Enterprise Architecture
** Chapter 23 Fabric
** Chapter 24 Assurance
* Part 8 Security
** Chapter 25 Access control
*** Network Security Design for Threat Defense

    *PIN = places in the network*
    - Branch: less secure
      attacks: endpoint malware, wireless like rogue AP and man in the middle, explotation of trust
    - Campus: large number of users from different categories
      attacks: phishing, web-based exploits, unauthorized network access, malware propagation, and botnet infestations.
    - Data center: most critical information assets, lots of servers
      attacks: data extraction, malware propagation, unauthorized network access (application compromise), botnet infestation (scrumping), data loss, privilege escalation, and reconnaissance
    - Edge: primary ingress and egress to internet
      attacks: web server vulnerabilities, distributed denial-of-service (DDoS) attacks, data loss, and MitM attacks
    - Cloud: require independent certification
      attacks: web server vulnerabilities, loss of access, data loss, malware, and MitM attacks
    - WAN: connects all the PINs together.
      attacks: malware propagation, unauthorized network access, WAN sniffing, and MitM attacks

    *Cisco SAFE secure domains*
    - Management: manage devices from centralized infrastructure
    - Security intelligence: Security intelligence provides detection of emerging malware and cyber threats
    - Compliance
    - Threat defense: provides this visibility through network traffic telemetry, file reputation, and contextual information (such as device types, locations, users, identities, roles, privileges levels, login status, posture status
    - Secure services: access control, virtual private networks
      
    *Protection during attack phases*
    - Before: stablishing policies and implementing prevention to reduce risk. Full knowledge of the assets to be protected and threats is required.
    - During: Threat analysis and incident response
    - After: ability to detect, contain, and remediate an attack. Lessons learned should be incorporated
      
**** Cisco Talos
     Security team that analizes security threats and creates a thread that is fed into cisco security products

**** Cisco threat grid
     Software that statically and dynamically analizes files for threat detection.
     Uses information from Talos
     Runs files in a sandbox with special instrumentation

**** Advanced malware protection
     Database connected to Talos and threat grid. Used to analyze files and detect malware.

**** Cisco AnyConnect
     VPN Client that also offers endpoint compliance controlling.

**** Cisco Umbrella
     DNS server cluster run by cisco

**** Web security appliance
     Next generation firewall that is connnected to Talos and the threat grid
     Offers:
     - Web reputation filters
     - Web filtering
     - Application visibility and control, used to control internet access

**** Cisco email security appliance
**** Next-Generation Intrusion Prevention System (NGIPS)
     - Real-time contextual awareness
     - Advanced threat protection
     - Intelligent security automation
     - Unparalleled performance and scalability
     - Application visibility and control (AVC) and URL filtering

**** Next-Generation Firewall (NGFW)
     - Standard firewall capabilities such as stateful inspection
     - An integrated IPS
     - Application-level inspection
     - The ability to leverage external security intelligence to address evolving security threats

**** Cisco Stealthwatch
     is a collector and aggregator of network telemetry data that performs network security analysis and monitoring
     - Real-time threat detection
     - Incident response and forensics
     - Network segmentation
     - Network performance and capacity planning
     - Ability to satisfy regulatory requirements

**** Cisco Identity Services Engine (ISE)
     is a security policy management platform that provides highly secure network access control (NAC) to users and devices across wired, wireless, and VPN connections

*** Network Access Control (NAC)
**** 802.1x
     is a standard for port-based network access control (PNAC) that provides an authentication mechanism for local area networks (LANs) and wireless local area networks (WLANs)

     *Extensible Authentication Protocol (EAP)*:
     This message format and framework defined by RFC 4187 provides an encapsulated transport for authentication parameters.
     *EAP method* (also referred to as EAP type):
     Different authentication methods can be used with EAP
     *EAP over LAN (EAPoL)*: 
     This Layer 2 encapsulation protocol is defined by 802.1x for the transport of EAP messages over IEEE 802 wired and wireless networks
     *RADIUS protocol*: 
     This is the AAA protocol used by EAP
     
     *Suplicant*: software on the device trying to access the network through EAPoL
     *Authenticator*: network appliance the suplicant connects to. The appliance makes no decisions, and allows or denys access only on command of the authentication server
     *Authentication Server*: RADIUS server that has the user database and authenticates the clients

     *Authentication process*:
     1. either the authentcator notices a port coming up or the supplicant sends an EAPoL message    AP Methods*:
     2. 
     3. packet is relayed over inside a radious packet.
     4. if successful, server returns a access-accept with optional parameters (downloadable ACLs). The authenticator opens the port

***** EAP methods
      Mostly based on TLS
      *EAP challenge-based authentication method* (EAP-MD5)
      uses the MD5 message-digest to encrypt the credentials. The supplicant doesn't have a way to authenticate the server (bad)
      *EAP TLS* (EAP-TLS)
      Uses PKI to provide mutual authentication. Very secure, high administrative overhead
      *EAP tunneled TLS* (EAP-FAST) (EAP-TTLS) (PEAP)
      - PEAP: only the server requires a certificate and builds a TLS tunnel over which authentication happens using inner auth methods
      *EAP inner authentication methods* (EAP-GTC) (EAP-MSCHAPv2) (EAP-TLS)
      + EAP-MSCHAPv2 (PEAPv0): client credentials are sent over a MSCHAPv2 session. Used with Microsoft Active Directory
      + EAP-GTC (PAPv1): created as an alternative to EAP-MSCHAPv2, can use any identity store
      + EAP-TLS: tunnel over tunnel, same as normal EAP-TLS
      + EAP-FAST: cisco propietary, allows for faster reauthentication and supports roaming. Forms a TLS tunnel and can reauthenticate using protected access credentials (PACs), similar to a secure cookie.
      + EAP-TTLS: similar to PEAP but less supported. Allows for non inner-EAP auth methods like PAP, CHAP and MS-CHAP
      
***** EAP chaining
      included in EAP-FAST, supports machine and user auth inside a single TLS tunnel

***** MAC authentication bypass (MAB)
      enables port-based access using the MAC-address of an endpoint, used as fallback for 802.1x
      1. switch tries to use 802.1x and
      2. the switch opens a port for only one packet, learns the mac address and discards it. After that sends a RADIUS access request using the learned mac address
      3. the RADIUS server determines if the device can access the network.

**** Web Authentication
     can be used as fallback for 802.1x
***** Local web auth (LWA)
      the switch redirects the user to a web page. Then sends the request itself to the RADIUS server. Limited options.
***** Central web authentication with cisco ISE (CWA)
      offers advanced services. Process:
      1. 802.1x fails
      2. switch performs MAB
      3. auth server sends a radius result, including an URL redirection to the centralized server
      4. endpoint gets ip over DHCP
      5. credentials are entered on the browser
      6. ISE sends a reauthentication challenge to the switch
      7. switch sends a new MAB request to the ISE and it issues a final authorization result to the switch.
**** Enhanced Flexible Authentication (FlexAuth)
     enables multiple methods concurrently for fastness

**** Cisco identity-based networking services (IBNS)
     Combination of Enhanced Flexauth, Common classification policy language and ISE
***** Cisco TrustSec
      Uses Security Group Tags (SGT) to enforce firewall rules. A SGT should represent the context of the user/device and it's function. Department based firewalling 

      *ingress classification*
      process of assigning SGT to users or endpoints.
      - Dynamic: downloaded as an authorization option from the ISE
      - Static: used where 802.1x or MAB are not required (Data-Center).

      *Propagation*
      process of communicating the mappings to the TrustSec network.
      - inline tagging: switch inserts the SGT tag into the frame. Only supported by cisco switches with ASIC with support for TrustSec.
      - SGT Exchange protocol (SXP): TCP-based peer-to-peer protocol for devices that don't support inline tagging.

      *Egress enforcement*
      enforced at the egress point of the TrustSec network
      - Security group ACL (SGACL): access lists provide filtering in routers and switches
      - Security group Firewall (SGFW): provides enforcement in firewalls. Requires tag based rules to be configured in the FW
**** MACsec
     standards-based layer 2 protocol encryption method. Allows for switches to encrypt traffic on the wire.
     Additional fields are added, this have to be supported by all the switches in the chain to work.
     Authentication with Galois Method Authentication Code (GMAC) or Galois/Counter Mode Advanced Encryption Standard (AES-GCM)

     *security tag fields*
     - MACsec Ethertype (first two octets): Set to 0x88e5, designating the frame as a MACsec frame
     - TCI/AN (third octet): Tag control information/association, designates version number if confidentiality is used on it's own.
     - SL (fourth octet): short length field, designates the length
     - Packet Number (octets 5-8): numbering for replay protection and initializing vector
     - SCI (octets 9-16): secure channel identifier, for classifying the connection to the virtual port

     *keying mechanisms*
     + Security Association Protocol (SAP): proprietary cisco
     + MACsec key agreemant protocol (MKA): provides required session keys and manages the encryption keys. Supported between endpoint-switch and switch-switch

***** Downlink MACsec
      term used for the switch-endpoint link.
      Handled by the MKA protocol
      Both devices need to support MACsec
      Can be set as an authorization option

***** Uplink MACsec
      term used for switch-switch link
      uses SAP by default
** Chapter 26 Device access control and security
*** Access Control Lists
    Sequential list of access control entries (ACE) for packet classification
    Used for filtering, qos and nat
    
    + *numbered standard* can filter only on source ip, numbers 1-99 and 1300-1999
    + *number extended* can filter on source, destination, port, protocol and more. 100-199 and 2000-2699
    + *named* same as avobe but with names
    + *port acl* can use standard, extended, and names acls to filter on L2
    + *vlan acl* can use standard, extended, and names acls to filter vlans

    use wilcard masks to match patckets
    have to be applied to an interface

    the *any* keyword matches all packets, the *host* keyword matches only one host

    *PACL* port access control list act on L2 ports
    + do not support filter on control packets
    + only incomming traffic
    + only on hardware
    + do not support ipv6, arp or MPLS

    *VACL* vlan access control list
    implemeted using access maps. Maps use ACLs to as match statements and an action (forward or drop on the match), similar to route maps
*** PACL, VACL, and RACL Interaction
    if multiple acls are configured, the order is:
    on L2
    - inbound pactl
    - inbound vacl
    - outbound vacl

    on L3
    - inbound pactl
    - inbound vacl
    - inbound svi
    - outbound svi
    - outbound vacl
*** Terminal Lines
- Line con 0 (cty)
  serial console
- Line aux 0 (aux)
  connect through a modem
- Virtual lines (vty) 1 - 4
  for remote telnet or ssh access. Logical, no physical interface attached
**** Password types
*Type 0*: insecure, not encrypted and visible
*Type 5*: encrypted with md5
*Type 7*: weak encryption, cisco proprietary
*Type 8*: secure, uses sha-256 algorithm to encrypt
*Type 9*: secure uses SCRYPT algorithm to encrypt
**** Priviledge levels and role base access (RBAC)
*Level 0*: disable, enable, help, exit and logout commands
*Level 1*: EXEC mode, no configuration changes allowed
*Level 15*: Priviledged EXEC mode, anything goes

Levels 2-14 can be used to create custom permission levels

EXEC timeout configures the session timeouts
Absolute timeout terminates a session even if it's being used

*** AAA Authentication, Authorization and Accounting
*Authentication*: Enables a user to be identified and verified prior to being granted access to a network device and/or network services.
*Authorization*: Defines the access privileges and restrictions to be enforced for an authenticated user.
*Accounting*: Provides the ability to track and log user access, including user identities, start and stop times, executed commands (that is, CLI commands), and so on. In other words, it maintains a security log of events.
**** TACACS+
tcp on port 49
can separate authentication, authorization, and accounting into different functions
**** Radius
IETF standard
used for EAP
Client/Server model
Must return all authentication parameters in a single reply
Good for authentication but bad for authorization
*** Zone Based Firewall (ZBFW)
    integrated firewall solution for cisco devices
    uses zones to establish relationships
    can track connection states
**** Firewall zones
     - Self zone: includes all routers ip addresses and is used for support and management
     - Default zone: includes all interfaces that are not member of any other zone. Default policy drop
     - other zones: can be created
**** Configuration
     create a zone
     create a class-map. Those are similar to route maps, they use acls for (not) matching packets and define what is done if the packet is matched
     class-maps can be match-any (bool OR) or match-all (bool AND)
     policy-maps have pollicy drop, pass (allow) and inspect. Inspect tracks the connection state
     policy-maps apply the fw configuration to the class-map
     apply a policy map to a traffic flow. Those have a direction and have to be configured in both ways for bidirectional communication
*** Control plane policing (CoPP)
    is a QoS policy applied to traffic to or sourced from the router, used to protect the CPU resources
    uses class-maps to classify traffic and applies the policies with policy-maps
    to test the policies, the *violate* policy can be set to transmit to ensure no disruptions. This policy can be monitored to set a baseline
    policy-maps have a default class default for traffic that doesn't match any other class
* Part 9 SDN
** Chapter 27 Virtualization
*** Terminology
**** Network functions virtualization (NFV)
framework cretated by the european telecommunications standards institute to decouple network functions from propietary appliances
**** Virtual network function (VNF)
virtual or software version of an NFV
**** Virtualized infrastructure manager (VIM)
manages NFV resources
**** VNF Performance
two patterns:
- North-south: typical traffic when an external client requests information from a service
- East-west: traffic that is internal to the network, for example a backend service doing db queries
*** OVS-DPDK
OVS with DPDK operates entirely in user space. The DPDK Poll Mode Driver (PMD) in OVS polls for data that comes into the pNIC and processes it, bypassing the network stack
bypasses the kernel
requires one or more CPU cores dedicated to polling and handling the incoming data
*** PCI Passthrough
allows the virtualized system to attach directly to the pNIC, bypassing the hypervisor
downside, only one VNFs per pNIC
*** SR-IOV
allows multiple VNF to share one pNIC
emulates multiple PCIe devices, each VNF gets an emulated pNIC
emulated devices are called _virtual functions_ and physical devices _physical functions_
*** Cisco Enterprise Network Functions Virtualization (ENFV)
based on the ETSI NFV, runs multiple network functions in a single x*G platform
**** Components
- Management and orchestration
- VNFs
- Network functions virtualization infrastructure software (NFVIS) (Platform OS)
- Hardware resources
** Chapter 28 Programability concepts
*** REST API
- GET: Requests data
- POST: submits data
- PUT: replaces data
- PATCH: appends data
- DELETE: removes data
** Chapter 29 Automation tools
PPDIOO (Prepare, Plan, Design, Implement, Observe, Optimize)
*** Embeded Event Manager (EEM)
engine running on cisco devices that allows the writing of applets and tcl scripts
executes cli commands when certain events are triggered
can be run manually and trigger tcl scripts
*** Puppet
agent based
*** Puppet Bolt
Agentless mode for Puppet
Orchestrator-driven tasks use the Puppet architecture, used for large-scale
Standalone tasks connect directly to the devices and don't need a puppet environment
*** Chef
written in Ruby and Erlang, recipes are written in Ruby
both push and pull possible
client/server model 
*** SaltStack
Uses an agent and server mode
Nodes are called minions
Reactors live on the _master_ and listens to _beacons_ on the nodes that inform of configuration changes
Grains run on the nodes and gather information to report to the master
Pillars store data that the minon can retrieve from the maste
*** Saltstack ssh
Agentless option, requires python on the target node
*** Ansible
Agentless
** Chapter 30 Final preparation
